# Generated by Django 3.2 on 2023-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230324_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyrateapproval',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
