# Generated by Django 3.2 on 2023-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230417_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
