# Generated by Django 3.2 on 2023-04-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_worker_approved_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
