# Generated by Django 3.2 on 2023-04-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230324_1308'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_time']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_time',
            new_name='last_updated_time',
        ),
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('in-progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.worker'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskRequest',
        ),
    ]
